### ISSUE TITLE
issue in downloading the latest release

### ISSUE THREAD

**Issue by Ahmedfir** [smartshark/usage-examples#4]
Hello,

I am trying to download the dataset from your website.
The link to the small one seems to be broken: https://data.goettingen-research-online.de/download/smartshark_2_2_small.agz
The large one starts downloading up to 10 Gb then fails.

Do you have any other links/alternatives? Do you have any recommendations for the download?

Thank you in advance!

**Comment by atrautsch** [comment]
Hi,
you can try [this](http://141.5.100.155/smartshark_2_2_small.agz) alternative link. We also have one for the [large](http://141.5.100.155/smartshark_2_2.agz) version.
Let us know if this works for you.

**Comment by Ahmedfir** [comment]
Closing as "Not an issue"

Hi,
Thank you for your answer. 
The download worked with the previous links, this time. 
Thank you again!
